---
title: "Marta Pecina's initial neurofeedback/placebo experiment"
author: "Alex Dombrovski"
date: "1/20/2017"
output:
pdf_document: default
latex_engine: xelatex
html_document: default
---

```{r options}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, tidy = TRUE)

```

## analysize and plot estimated marginal means in Marta's placebo/NF data

``` {r load_libraries}
library(nlme)
library(xtable)
library(lme4)
library(readr)
library(ggplot2)
library(lsmeans)
library(car)
```
# import behavior, individual differences and betas data, check betas

```{r import_data}
df <- read_csv("~/Google Drive/skinner/Pecina_k/alex_behav_full_merge_with_betas.csv")
df$Sex <- as.factor(df$Sex)
df$subject<- as.factor(df$subject)
# rename ROIs
df$visual1 <- df$CuneusVisual
df$motor2 <- df$PostcentralMotor
df$cing3 <- df$LRCingulateMedFrontalGy
df$crbl4 <- df$Cerebellum
df$str5 <- df$LLentiformNucPutamen
df$striatum <- df$str5
df$postc6 <-df$RPostcentral
df$crbl7 <- df$Cerebellum2
df$thal8 <- df$LThalamus

ggplot(data = df, mapping = aes(df$cing3,df$str5)) +geom_point(mapping = aes(df$cing3,df$str5))

```
Predict feedback ratings.
``` {r feedback}
# nm1 <- (lmer(feedback_rating ~ stim_rating + feedback + feedback_ratinglag + (1 +feedback + stim_rating |subject), df))
# summary(nm1)
# car::Anova(nm1)

nm2 <- (lmer(feedback_rating ~ stim_rating*stim + feedback + feedback_ratinglag + (1 +feedback + stim_rating |subject), df))
summary(nm2)
car::Anova(nm2)
# anova(nm1,nm2)

ls_nm2 <- lsmeans(nm2,"stim_rating",by = "stim", at = list(stim_rating = c(-2,-1,0,1,2)))
plot(ls_nm2, type ~ stim_rating, horiz=F, ylab = "Mood ratings", xlab = "Expectancy")

nm3 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + visual1*stim + (1 +feedback + stim_rating |subject), df))
summary(nm3)
car::Anova(nm3)

nm4 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + motor2*stim + (1 +feedback + stim_rating |subject), df))
summary(nm4)
car::Anova(nm4)
anova(nm3,nm4)




nm5 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + striatum*stim + (1 +feedback + stim_rating |subject), df))
summary(nm5)
car::Anova(nm5)
anova(nm4,nm5)

ls_nm5 <- lsmeans(nm5,"stim",by = "striatum", at = list(striatum = c(1,5,10)))

``` 
Save results

``` {r plot_str_feedback}
setwd("/Users/localadmin/Google Drive/skinner/Pecina_k/results/")

# pdf("str_modulation.pdf", width=5, height=3.5)
plot(ls_nm5, type ~ stim, horiz=F, ylab = "Mood ratings", xlab = "infusion", main = "Striatal activity modulates effect of infusion")
# dev.off()

# nm6 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + visual1*stim  + (1 +feedback + stim_rating |subject), df))
# summary(nm6)
# car::Anova(nm6)
# anova(nm4,nm6)

```

Expectancy rating models

``` {r expectancy}
em1<- (lmer(stim_rating ~ stim + feedback_ratinglag*striatum  + (1 +stim  |subject), df))
summary(em1)
car::Anova(em1)

em2<- (lmer(stim_rating ~ stim + feedback_ratinglag*striatum + stim_diff  + (1 +stim  |subject), df))
summary(em2)
car::Anova(em2)

ls_em2 <- lsmeans(em2,"feedback_ratinglag",by = "striatum", at = list(striatum = c(1,5,10),feedback_ratinglag = c(-2,0,2)))
# pdf("str_modulation_feedback_rating_lag.pdf", width=5, height=3.5)
plot(ls_em2, type ~ stim, horiz=F, ylab = "Expectancy ratings", xlab = "Previous mood ratings", main = "Striatal activity modulates effect of earlier mood")
# dev.off()

# include indiv. differences in feedback rating models

# rescale
numcols <- grep("^c\\.",names(df))

# df$apathy <- scale(df$ApathyEvaluationScale)

im1 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + (1 +feedback + stim_rating |subject), df))
summary(im1)
car::Anova(im1)

im2 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + df$DAS7*feedback + (1 +feedback + stim_rating |subject), df))
summary(im2)
car::Anova(im2)
# anova(im1,im2)


# im3 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + df$YearsOfEd*feedback*stim + (1 +feedback + stim_rating |subject), df))
# summary(im3)
# car::Anova(im3)
# anova(im1,im3)
# ls_im3 <- lsmeans(im3,"stim",by = "df$YearsOfEd", at = list(df$YearsOfEd = c(8,13,18)))

ls_nm2 <- lsmeans(nm2,"stim_rating",by = "stim", at = list(stim_rating = c(-2,-1,0,1,2)))
plot(ls_nm2, type ~ stim_rating, horiz=F, ylab = "Mood ratings", xlab = "Expectancy")


# im4 <- (lmer(feedback_rating ~ stim_rating*stim + feedback +feedback_ratinglag + df$striatum*stim + df$YearsOfEd*stim + (1 +feedback + stim_rating |subject), df))
# summary(im4)
# car::Anova(im4)
# anova(im3,im4)

ls_nm5 <- lsmeans(nm5,"stim",by = "striatum", at = list(striatum = c(1,5,10)))

```


## check Apathy ratings

``` {r check_apathy}
ggplot(data = df, mapping = aes(df$ApathyEvaluationScale,df$subject)) +geom_point(mapping = aes(df$ApathyEvaluationScale,df$subject))

ggplot(data = df, mapping = aes(df$ApathyEvaluationScale,df$Age)) +geom_point(mapping = aes(df$ApathyEvaluationScale,df$Age))
```
